spring:
  profiles:
    active: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-2.c2iea9blmsmn.ap-northeast-1.rds.amazonaws.com:5432/commu-talk
    username: postgres
    password: postgres
