CREATE TABLE IF NOT EXISTS public.communities
(
    com_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) NOT NULL,
    category_id integer NOT NULL,
    CONSTRAINT communities_pkey PRIMARY KEY (com_id),
    CONSTRAINT communities_name_key UNIQUE (name)
)

CREATE TABLE IF NOT EXISTS public.categories
(
    category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) NOT NULL,
    hobby_id integer NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id),
    CONSTRAINT hobby_id FOREIGN KEY (hobby_id)
        REFERENCES public.hobbies (hobby_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
    
CREATE TABLE IF NOT EXISTS public.hobbies
(
    hobby_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT hobbies_pkey PRIMARY KEY (hobby_id)
)
    OWNER to postgres;